### ISSUE TITLE
touch-through-view doesn't work with react-native-navigation

### ISSUE THREAD

**Issue by simonhoss** [simonhoss/react-native-touch-through-view#3]
This component doesn't work with react-native-navigation. I will try to figure out.

**Comment by derekblank** [comment]
Thanks for looking into this. I was experimenting with some things as well. My hope is that the principle of using `getHitSlopRect` should still work and it's just a matter of applying the TouchThrough interface to the proper activity. Let me know if I can be of assistance.

**Comment by simonhoss** [comment]
Hi. I had a chance to take a look. It seems that it is more complicated to get it run, but not impossible! Maybe you can use https://reactnavigation.org/ with that I can confirm that it works!

**Comment by derekblank** [comment]
I spun up a quick example with react-navigation and it runs perfectly on Android, so we can say your approach using `TouchThroughTouchHandlerInterface` works:

![touchthroughview](https://user-images.githubusercontent.com/643285/38772830-873a9076-3ff4-11e8-8abf-1ad06a8b7e3a.gif)

Since we know the `getHitSlopRect` principle works, I believe the issue lies with react-native-navigation requiring `MainActivity` to extend `com.reactnativenavigation.controllers.SplashActivity` instead of `ReactActivity`.

Running the application with react-native-navigation produces this error:

<img width="267" alt="screen shot 2018-04-14 at 3 19 56 pm" src="https://user-images.githubusercontent.com/643285/38772959-64522468-3ff7-11e8-84b6-6a48b6af5753.png">


After the app launches past the splash screen, react-native-navigation [transfers the current activity](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=why-overriding-these-methods-in-mainactivity-won39t-work) to `NavigationActivity` [via these methods](https://github.com/wix/react-native-navigation/blob/0557b61ab223bf3669a25279ad8562b5c87be0e9/android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java#L527-L550):

```
    public static void isAppLaunched(Promise promise) {
        final boolean isAppLaunched = SplashActivity.isResumed || NavigationActivity.currentActivity != null;
        promise.resolve(isAppLaunched);
    }

    public static void isRootLaunched(Promise promise) {
        promise.resolve(NavigationActivity.currentActivity != null);
    }

    public static void getCurrentlyVisibleScreenId(final Promise promise) {
        final NavigationActivity currentActivity = NavigationActivity.currentActivity;
        if (currentActivity == null) {
            promise.resolve("");
            return;
        }
        NavigationApplication.instance.runOnMainThread(new Runnable() {
            @Override
            public void run() {
                WritableMap map = Arguments.createMap();
                map.putString("screenId", currentActivity.getCurrentlyVisibleScreenId());
                promise.resolve(map);
            }
        });
    }
```

Can you think of a way we could get `NavigationActivity` to implement `TouchThroughTouchHandlerInterface`? It may work if we can apply the TouchThroughTouchHandler there. I'm open to forking and modifying the react-native-navigation library if needed. *Edit:* I was also thinking we could listen for the current activity and apply the TouchThroughTouchHandler there. I'm not a Java expert so apologies if these are bad ideas. :) 

I also discovered react-native-navigation provides [activity lifecycle callbacks](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=activity-lifecycle-and-onactivityresult).

Or, do you have any other guesses as to where the issue lies? I'm interested in what you think the problem could be.

**Comment by simonhoss** [comment]
Can you please check this example: https://github.com/simonhoss/react-native-touch-through-view/tree/master/example-react-native-navigation

It should work with that!

**Comment by derekblank** [comment]
Brilliant, that works perfectly! Thank you so much for your help on this.

**Comment by simonhoss** [comment]
Nice! Please show me the app when its finished! ;)

**Comment by ishantsagar** [comment]
@simonhoss We're getting this issue repeatedly with multiple apps even though we're using `react-navigation`. Can you please suggest a fix?

**Comment by simonhoss** [comment]
@ishantsagar did you follow the android installation guide?

**Comment by ishantsagar** [comment]
@simonhoss Yes, exactly and moreover I am not able to reproduce this crash anyhow, and its only affecting users on store as I could see through my crash loggers.

**Comment by simonhoss** [comment]
@ishantsagar that sounds really strange. Can you maybe share me the exact crash log including android version?

**Comment by maxbeech** [comment]
Hey @simonhoss, absolutely fantastic fork, thanks!

I have been using the base repo, but now trying to move to yours thanks to your great fixes for Android.

I am getting the same error message on Android only, but I am using [React Navigation](https://reactnavigation.org/) (as it is implemented within the [Ignite Boilerplate](https://github.com/infinitered/ignite-ir-boilerplate-bowser), which I am using).

Do you have any idea how I adapt your Android installation for React Navigation please?

Thanks a ton!
Max
![screenshot_1538660630](https://user-images.githubusercontent.com/8388201/46478036-fbc07d80-c7e3-11e8-86bd-a99857ca33bd.png)

**Comment by simonhoss** [comment]
@maxbeech Can you please create a sample repo? I will then pull it and see whats going on. 

Thank you in advance

**Comment by maxbeech** [comment]
@simonhoss Sure thing! Thanks so much for your help.

I have just successfully recreated the issue on a fresh install. Any help would be hugely appreciated!
Repo: https://github.com/maxbeech/ignite-bowser-examples

Thanks a ton!

**Comment by simonhoss** [comment]
Thank you for the repo. I will have a look on it. Unfortunately I can only start in the beginning of next week. Because I'm not at home this weekend 😞

**Comment by maxbeech** [comment]
No worries Simon, really appreciate it and thanks for letting me know that.

Max

**Comment by maxbeech** [comment]
Hi Simon! Don't suppose you've had a chance to take a look have you please?

No worries if not - just thought I'd let you know that I haven't been able to resolve the issue as yet.

Many thanks,
Max

**Comment by simonhoss** [comment]
Hi. I have you in my mind ;)
Hopefully I can do something tomorrow or on thursday!

**Comment by maxbeech** [comment]
Thanks so much Simon!! Really appreciated 💯💯

**Comment by simonhoss** [comment]
Hi

Here is my commit: https://github.com/simonhoss/ignite-bowser-examples/commit/c15aa3073d7ad8750259a777b8581120d17d77d5 

One problem is also that the button was too near to the rows. It seems that there is a position problem maybe with the flex? But this example should work for now.

**Comment by maxbeech** [comment]
Amazing thanks so much mate!! Will give it a go as soon as I can and post
pack.

Best,
Max

**Comment by maxbeech** [comment]
(Finally) was able to implement the fix and it works brilliantly!
Thanks a tonne Simon really appreciated 🎉

**Comment by simonhoss** [comment]
Awesome. You're welcome. I would like to see your app when its finished 😉

**Comment by maxbeech** [comment]
It’s actually live already!

Update out today with your fork integrated!! Would love any feedback you
have on it! > getintro.app/download

Many thanks again!
Max
